#!/usr/bin/env bash
# Creates the .agent/ and .ai-context/ folder structure at a target project root.
# Copies the static, skeleton-only .ai-context templates.
# Does NOT write .agent content — that's stack-specific and generated by Claude
# directly (see references/agent_content_guide.md), because it must be filled in,
# not skeletal.
#
# Usage: scaffold.sh <target-project-root>

set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${1:?Usage: scaffold.sh <target-project-root>}"

mkdir -p "$TARGET/.agent/rules"
mkdir -p "$TARGET/.agent/workflows"
mkdir -p "$TARGET/.ai-context/specs"
mkdir -p "$TARGET/.ai-context/plans"
mkdir -p "$TARGET/.ai-context/tasks"
mkdir -p "$TARGET/.ai-context/test_cases"
mkdir -p "$TARGET/.ai-context/decisions"

# Static .agent file (identical regardless of stack)
cp "$SKILL_DIR/assets/agent/auto-log.md" "$TARGET/.agent/rules/auto-log.md"

# Static .ai-context skeleton templates (content to be filled in later)
cp "$SKILL_DIR/assets/ai-context/constitution.md"      "$TARGET/.ai-context/constitution.md"
cp "$SKILL_DIR/assets/ai-context/project_context.md"   "$TARGET/.ai-context/project_context.md"
cp "$SKILL_DIR/assets/ai-context/architecture.md"      "$TARGET/.ai-context/architecture.md"
cp "$SKILL_DIR/assets/ai-context/BRD.md"                "$TARGET/.ai-context/BRD.md"
cp "$SKILL_DIR/assets/ai-context/status.md"             "$TARGET/.ai-context/status.md"
cp "$SKILL_DIR/assets/ai-context/prompt_history.md"     "$TARGET/.ai-context/prompt_history.md"
cp "$SKILL_DIR/assets/ai-context/prompts.md"            "$TARGET/.ai-context/prompts.md"

cp "$SKILL_DIR/assets/ai-context/specs/_TEMPLATE.spec.md"          "$TARGET/.ai-context/specs/_TEMPLATE.spec.md"
cp "$SKILL_DIR/assets/ai-context/specs/_TEMPLATE.hotfix.spec.md"   "$TARGET/.ai-context/specs/_TEMPLATE.hotfix.spec.md"
cp "$SKILL_DIR/assets/ai-context/plans/_TEMPLATE.plan.md"          "$TARGET/.ai-context/plans/_TEMPLATE.plan.md"
cp "$SKILL_DIR/assets/ai-context/tasks/_TEMPLATE.tasks.md"         "$TARGET/.ai-context/tasks/_TEMPLATE.tasks.md"
cp "$SKILL_DIR/assets/ai-context/test_cases/_TEMPLATE.test_cases.md" "$TARGET/.ai-context/test_cases/_TEMPLATE.test_cases.md"
cp "$SKILL_DIR/assets/ai-context/test_cases/_integration.md"       "$TARGET/.ai-context/test_cases/_integration.md"
cp "$SKILL_DIR/assets/ai-context/decisions/_TEMPLATE_ADR.md"       "$TARGET/.ai-context/decisions/_TEMPLATE_ADR.md"

echo "Scaffolded .agent/ and .ai-context/ at: $TARGET"
echo "Still needed (generated by Claude, not this script):"
echo "  $TARGET/.agent/rules/int-standards.<stack-slug>.md"
echo "  $TARGET/.agent/rules/.agentignore"
echo "  $TARGET/.agent/workflows/code-review.md"
echo "  $TARGET/.agent/workflows/generate-tests.md"
echo "  $TARGET/.agent/workflows/generate-plan.md"
